### ISSUE TITLE
Thanks for your nice work, but when i compile .cs file it told me "supercontroller dones not contain a definition of a IsSimulationPaused "

### ISSUE THREAD

**Issue by 1475015695** [arijoon/foto2vam#1]
![image](https://user-images.githubusercontent.com/34376638/116515878-75b73580-a8ff-11eb-96b7-f5914d657da3.png)

**Comment by arijoon** [comment]
That is likely with the game assembly itself, so you may need to import additional dependencies to compile, its not part of this project's scripts
